(define (vector-for-each4/itr! pos len proc a b c d)
  (unless (= pos len)
    (proc (vector-ref a pos)
          (vector-ref b pos)
          (vector-ref c pos)
          (vector-ref d pos))
    (vector-for-each4/itr! (+ pos 1) len proc a b c d)))

(define (vector-for-each4 proc a b c d)
  (let ((len (min (vector-length a) (vector-length b)
                  (vector-length c) (vector-length d))))
    (vector-for-each4/itr! 0 len proc a b c d)))

(define (vector-for-each3/itr! pos len proc a b c)
  (unless (= pos len)
    (proc (vector-ref a pos)
          (vector-ref b pos)
          (vector-ref c pos))
    (vector-for-each3/itr! (+ pos 1) len proc a b c)))

(define (vector-for-each3 proc a b c)
  (let ((len (min (vector-length a) (vector-length b) (vector-length c))))
    (vector-for-each3/itr! 0 len proc a b c)))

(define (vector-for-each2/itr! pos len proc a b)
  (unless (= pos len)
    (proc (vector-ref a pos)
          (vector-ref b pos))
    (vector-for-each2/itr! (+ pos 1) len proc a b)))

(define (vector-for-each2 proc a b)
  (let ((len (min (vector-length a) (vector-length b))))
    (vector-for-each2/itr! 0 len proc a b)))

(define (vector-for-each1/itr! pos len proc a)
  (unless (= pos len)
    (proc (vector-ref a pos))
    (vector-for-each1/itr! (+ pos 1) len proc a)))

(define (vector-for-each1 proc a)
  (let ((len (vector-length a)))
    (vector-for-each1/itr! 0 len proc a)))

(define (vector-for-each proc a . args)
  (if (null? args)
    (vector-for-each1 proc a)
    (let ((b (car args))
          (bb (cdr args)))
      (if (null? bb)
        (vector-for-each2 proc a b)
        (let ((c (car bb))
              (cc (cdr bb)))
          (if (null? cc)
            (vector-for-each3 proc a b c)
            (let ((d (car cc))
                  (dd (cdr cc)))
              (if (null? dd)
                (vector-for-each4 proc a b c d)
                (error "Too many...")))))))))
