# Detect target platform

macro(yuni_detect_platform var)
    if(NOT CMAKE_SIZEOF_VOID_P)
        message(SEND_ERROR "WHY")
    endif()

    if(WIN32)
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(${var} WIN64)
        elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
            set(${var} WIN32)
        else()
            message(SEND_ERROR "WHY")
        endif()
    elseif(CYGWIN)
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(${var} CYG64)
        elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
            set(${var} CYG32)
        else()
            message(SEND_ERROR "WHY")
        endif()
    else()
        set(${var} UNKNOWN)
    endif()
endmacro()
