#ifndef YUNIFFI_ABIV0_SYMFLAGS_H
#define YUNIFFI_ABIV0_SYMFLAGS_H

#include <yuniffi/util/bits.h>

/* Symbol flags */

/*  Core flags */
#define YUNIFFI_SYMBOL__TERMINATE  YUNIFFI_BIT(0)
#define YUNIFFI_SYMBOL__VALID      YUNIFFI_BIT(1)
#define YUNIFFI_SYMBOL__HAS_SIZE   YUNIFFI_BIT(2)
#define YUNIFFI_SYMBOL__HAS_OFFSET YUNIFFI_BIT(3)
#define YUNIFFI_SYMBOL__HAS_RESVD0 YUNIFFI_BIT(4)
#define YUNIFFI_SYMBOL__HAS_RESVD1 YUNIFFI_BIT(5)

/*  Common classes */
#define YUNIFFI_SYMBOL_AGGREGATE_MEMBER \
    (YUNIFFI_SYMBOL__VALID | \
     YUNIFFI_SYMBOL__HAS_SIZE | YUNIFFI_SYMBOL__HAS_OFFSET)
#define YUNIFFI_SYMBOL_TYPE \
    (YUNIFFI_SYMBOL__VALID | YUNIFFI_SYMBOL__HAS_SIZE)
#define YUNIFFI_SYMBOL_CONSTANT \
    (YUNIFFI_SYMBOL__VALID)
#define YUNIFFI_SYMBOL_CONSTANT_BLOB \
    (YUNIFFI_SYMBOL__VALID | YUNIFFI_SYMBOL__HAS_SIZE)

#define YUNIFFI_SYMBOL_TERMINATE YUNIFFI_SYMBOL__TERMINATE

#endif /* YUNIFFI_ABIV0_SYMFLAGS_H */
