(library (nmosh-r7b write)
         (export display write write-shared write-simple)
         (import  (rename (rnrs) 
                          (write write-simple))
                  (mosh))
(define write write/ss)         
(define write-shared write/ss))
