set(selfboot_KAWA "kawa/selfboot-entry.scm")
set(selfboot_CHIBI_SCHEME "chibi-scheme/selfboot-entry.scm")
set(selfboot_GOSH "gauche/selfboot-entry.scm")
set(selfboot_SAGITTARIUS "sagittarius/selfboot-entry.sps")
set(selfboot_CHEZ_SCHEME "chez/selfboot-entry.sps")
set(selfboot_MIT_SCHEME "mit-scheme/selfboot-entry.scm")
set(selfboot_S7 "s7/selfboot-entry.scm")
set(selfboot_RACKET "racket/selfboot-entry.rkt")
set(selfboot_CHICKEN_CSI "chicken/selfboot-entry.scm")
set(selfboot_CHICKEN5_CSI "chicken/selfboot-entry.scm")
set(selfboot_GSI "gambit/selfboot-entry.scm")
set(selfboot_GUILE "guile/selfboot-entry.sps")
set(selfboot_BIWASYUNI "biwascheme/selfboot-entry.scm")

set(arg_prog_CHEZ_SCHEME "--program")
set(arg_prog_CHICKEN_CSI "-script")
set(arg_prog_CHICKEN5_CSI "-script")
set(arg_prog_MIT_SCHEME "--load")
