set(selfboot_KAWA "kawa/selfboot-entry.scm")
set(selfboot_CHIBI_SCHEME "chibi-scheme/selfboot-entry.scm")
set(selfboot_GOSH "gauche/selfboot-entry.scm")
set(selfboot_SAGITTARIUS "sagittarius/selfboot-entry.sps")
set(selfboot_CHEZ_SCHEME "chez/selfboot-entry.sps")
set(selfboot_MIT_SCHEME "mit-scheme/selfboot-entry.scm")
set(selfboot_S7 "s7/selfboot-entry.scm")
set(selfboot_RACKET "racket/selfboot-entry.rkt")
set(selfboot_CHICKEN_CSI "chicken/selfboot-entry.scm")
set(selfboot_CHICKEN5_CSI "chicken/selfboot-entry.scm")
set(selfboot_GSI "gambit/selfboot-entry.scm")
set(selfboot_GUILE "guile/selfboot-entry.sps")
set(selfboot_GUILE3 "guile3/selfboot-entry.sps")
set(selfboot_BIWASYUNI "biwascheme/selfboot-entry.scm")
set(selfboot_DIGAMMA "digamma/selfboot-entry.sps")
set(selfboot_ICYC "cyclone/selfboot-entry.scm")
set(selfboot_STKLOS "stklos/selfboot-entry.scm")
set(selfboot_SCM "scm/selfboot-entry.scm")
set(selfboot_FOMENT "foment/selfboot-entry.scm")
set(selfboot_BIGLOO "bigloo/selfboot-entry.scm")

set(arg_prog_CHEZ_SCHEME "--program")
set(arg_prog_CHICKEN_CSI "-script")
set(arg_prog_CHICKEN5_CSI "-script")
set(arg_prog_MIT_SCHEME "--load")
set(arg_prog_GUILE3 "--r7rs")
set(arg_prog_ICYC "-s")
set(arg_prog_STKLOS "-cf")
set(arg_prog_SCM "-l")
set(arg_prog_BIGLOO "-i")
set(arg_ci_SCM "--no-symbol-case-fold")

set(arg_post_STKLOS "--")

set(arg_WAR_LAST_RUNNER_ICYC ON)
