try-r7rs-library-convert
nmosh:setup-r7rs-converter!
nmosh:r7rs-converter-install!
nmosh:r7rs-converter
library-name->filename
prefix-list
make-prefix-list
ca-preload-realize
ca-preload-register/core
ca-preload-register
ca-preload-disable
ca-preload-core
ca-archive-enable
do-ca-preload-core
ca-preload-enable
ca-preload-lookup-itr/core
ca-preload-lookup-itr
ca-preload-core-path
ca-preload-path
ca-preload-list
ca-preload-core-list
%ca-gen-preload-path
preload-core-port
preload-core-offset
preload-core-list
preload-port
preload-offset
preload-list
ca-prepare-cache-dir
ca-load
ca-load/disable-cache
ca-load/cache
ca-load-compiled-code/run
ca-load-compiled-code
ca-runcache
for-each1-tail
ca-need-update?
ca-need-update?-check
ca-expand/compile-for-cache
ca-read-all
ca-makecache
cachename-shorten
ca-scandeps
ca-scandeps-unit
ca-compose-libimports
ca-scandeps-begin
dbg-addsyms
dbg-syms
dbg-addfile
dbg-files
ca-filename->cachename
pathchop
ca-readobj
ca-writeobj
gen-tmpname
tmpname-counter
tmpname-base
has-cachepath?
ca-archive-begin
ca-archive-boot
ca-acc-disable?
ca-base-library-state
ca-base-libraries
ex:query-library-state
ex:unload-libraries!
CACHESUFFIX
CACHEDIR
CACHEPATH
nmosh-cache-path
mosh-cache-dir
nmosh-cache-dir
pathsep
make-absolute-path
compose-path
RUNPATH
strsep
absolute-path?
path-absolute
make-extended-path
pathfinish
pathfilter
CHR-ENVPATHSEP
run-win32-np?
rename-library
rename-library0
set-library-rename-table!
library-rename-table
target-os
DEBUGMODE-ON
PCK
DEBUGGING
ERRPORT
%%omit-library-version
ex:lookup-library
ex:register-library!
ex:import-libraries-for-run
ex:import-libraries-for
ex:imported
ex:library-invoked?-set!
ex:library-visited?-set!
ex:library-invoked?
ex:library-visited?
ex:library-build
ex:library-invoker
ex:library-visiter
ex:library-builds
ex:library-imports
ex:library-exports
ex:library-envs
ex:library-name
ex:make-library
ex:unspecified
id-debug
id-maybe-library
id-displacement
id-transformer-envs
id-colors
id-name
identifier?
make-identifier
make-identifier/debug
number->compact-form
debug-source-info
id-symbol
ex:free-prefix
ex:guid-prefix
ex:undefined-set!
ex:undefined
ex:unique-token
BOGUS
%verbose
%disable-acc
%nmosh-portable-mode
%nmosh-prefixless-mode
%loadpath
%getpid

