set-current-error-port!
object->pointer
pointer->object
set-annotation!
get-annotation
annotated-pair?
annotated-cons
file->string
ssl-supported?
ssl-socket?
socket-sslize!
process-terminate!
process-list
%monapi-stream-read
%monapi-stream-write
%monapi-stream-handle
%monapi-make-stream
%monapi-message-reply
%monapi-message-send-receive
%monapi-name-add!
%monapi-message-receive
%monapi-name-whereis
%monapi-message-send
write/ss
sexp-map/debug
sexp-map
current-dynamic-winders
gensym-prefix-set!
join-wraps
id->real-label
same-marks?
same-marks*?
nongenerative-rtd-set!
lookup-nongenerative-rtd
simple-struct-name
simple-struct-set!
simple-struct-ref
make-simple-struct
simple-struct?
shared-errno
bytevector-pointer
pointer-copy!
pointer-set-c-pointer!
pointer-set-c-double!
pointer-set-c-float!
pointer-set-c-long-long!
pointer-set-c-long!
pointer-set-c-int!
pointer-set-c-short!
pointer-set-c-char!
pointer-set-c-uint64!
pointer-set-c-uint32!
pointer-set-c-uint16!
pointer-set-c-uint8!
pointer-set-c-int64!
pointer-set-c-int32!
pointer-set-c-int16!
pointer-set-c-int8!
pointer-ref-c-pointer
pointer-ref-c-double
pointer-ref-c-float
pointer-ref-c-unsigned-long-long
pointer-ref-c-signed-long-long
pointer-ref-c-unsigned-long
pointer-ref-c-signed-long
pointer-ref-c-unsigned-int
pointer-ref-c-signed-int
pointer-ref-c-unsigned-short
pointer-ref-c-signed-short
pointer-ref-c-unsigned-char
pointer-ref-c-signed-char
pointer-ref-c-int64
pointer-ref-c-int32
pointer-ref-c-int16
pointer-ref-c-int8
pointer-ref-c-uint64
pointer-ref-c-uint32
pointer-ref-c-uint16
pointer-ref-c-uint8
integer->pointer
pointer->integer
pointer?
file-stat-ctime
file-stat-atime
file-stat-mtime
file-size-in-bytes
file-writable?
file-executable?
file-readable?
file-regular?
file-symbolic-link?
file-directory?
create-symbolic-link
rename-file
delete-directory
create-directory
vector-set!
vector-ref
vector-length
make-vector
mutex-unlock!
mutex-try-lock!
mutex-lock!
make-mutex
mutex?
condition-variable-notify-all!
condition-variable-notify!
condition-variable-wait!
make-condition-variable
whereis
register
vm-self
main-vm?
vm-join!
vm-set-value!
vm?
vm-start!
make-vm
socket-port
socket-shutdown
socket-close
socket-send
socket-recv!
socket-recv
os-constant
make-server-socket
make-client-socket
socket-accept
socket?
mosh-executable-path
time-usage
list-tail
list-ref
put-datum
make-custom-textual-input/output-port
make-custom-binary-input/output-port
open-file-input/output-port
modulo
remainder
quotient
transcoder-error-handling-mode
transcoder-eol-style
transcoder-codec
write-char
put-char
put-bytevector
native-transcoder
port-transcoder
port?
textual-port?
output-port?
host-os
%ffi-error
%ffi-close
%ffi-free-c-callback-trampoline
%ffi-make-c-callback-trampoline
%ffi-free
%ffi-malloc
%ffi-supported?
%ffi-call
%ffi-lookup
%ffi-open
open-bytevector-input-port
lookahead-u8
port-eof?
input-port?
binary-port?
set-current-directory!
current-directory
%getpid
%pipe
%waitpid
%exec
%fork
local-tz-offset
microseconds
buffer-mode?
native-eol-style
fast-equal?
print-stack
disasm
ungensym
vector-fill!
string-copy
make-polar
expt
atan
angle
magnitude
sqrt
acos
asin
tan
cos
sin
log
exp
round
truncate
ceiling
floor
denominator
numerator
div0
div
abs
odd?
even?
bytevector-ieee-double-set!
bytevector-ieee-double-native-set!
bytevector-ieee-single-set!
bytevector-ieee-single-native-set!
bytevector-ieee-double-ref
bytevector-ieee-double-native-ref
bytevector-ieee-single-ref
bytevector-ieee-single-native-ref
fxreverse-bit-field
fxrotate-bit-field
fxarithmetic-shift-right
fxarithmetic-shift-left
fxarithmetic-shift
fxcopy-bit-field
fxbit-field
fxcopy-bit
fxbit-set?
fxfirst-bit-set
fxlength
fxbit-count
fxif
fxxor
fxior
fxand
fxnot
fxmod0
fxdiv0
fxmod
fxdiv
fx-
fx*
fx+
fxmin
fxmax
fxeven?
fxodd?
fxnegative?
fxpositive?
fxzero?
fx<=?
fx>=?
fx<?
fx>?
fx=?
integer-valued?
rational-valued?
real-valued?
integer?
rational?
real?
complex?
bitwise-arithmetic-shift
bitwise-arithmetic-shift-right
bitwise-arithmetic-shift-left
bitwise-first-bit-set
bitwise-length
bitwise-bit-count
bitwise-xor
bitwise-ior
bitwise-and
bitwise-not
fixnum->flonum
flexpt
flsqrt
flatan
flacos
flasin
fltan
flcos
flsin
fllog
flexp
flround
fltruncate
flceiling
flfloor
fldenominator
flnumerator
flmod0
fldiv0
flmod
fldiv
flabs
fl/
fl-
fl*
fl+
flmin
flmax
flnan?
flinfinite?
flfinite?
fleven?
flodd?
flnegative?
flpositive?
flzero?
flinteger?
fl<=?
fl>=?
fl>?
fl<?
fl=?
real->flonum
finite?
infinite?
nan?
inexact
exact
inexact?
exact?
imag-part
real-part
make-rectangular
greatest-fixnum
least-fixnum
fixnum-width
bignum?
fixnum?
flonum?
rational?
get-string-n
fasl-read
fasl-write
make-compiler-instruction
make-instruction
close-port
utf32->string
utf16->string
string->utf32
string->utf16
null-terminated-utf8->string
null-terminated-bytevector->string
utf8->string
string->utf8
string->bytevector
bytevector->string
bytevector-s64-native-set!
bytevector-u64-native-set!
bytevector-s64-set!
bytevector-u64-set!
bytevector-s64-native-ref
bytevector-u64-native-ref
bytevector-s64-ref
bytevector-u64-ref
bytevector-s32-native-set!
bytevector-u32-native-set!
bytevector-s32-set!
bytevector-u32-set!
bytevector-s32-native-ref
bytevector-u32-native-ref
bytevector-s32-ref
bytevector-u32-ref
bytevector-s16-native-set!
bytevector-u16-native-set!
bytevector-s16-set!
bytevector-u16-set!
bytevector-s16-native-ref
bytevector-u16-native-ref
bytevector-s16-ref
bytevector-u16-ref
u8-list->bytevector
bytevector->u8-list
bytevector-s8-set!
bytevector-s8-ref
bytevector-u8-set!
bytevector-u8-ref
bytevector-copy
bytevector-copy!
bytevector-fill!
bytevector=?
bytevector-length
make-bytevector
make-bytevector
native-endianness
standard-library-path
current-directory
bytevector?
get-datum
get-line
get-string-all
get-string-n!
get-string-n
lookahead-char
get-char
min
max
/
*
-
+
=
>=
>
<=
<
throw
hashtable-hash-function
hashtable-equivalence-function
hashtable-keys
hashtable-clear!
hashtable-mutable?
hashtable-copy
hashtable-contains?
hashtable-delete!
hashtable-size
hashtable?
make-hashtable
set-symbol-value!
symbol-value
list-transpose+
$local-ref
$label
pass1/find-symbol-in-lvars
pass3/compile-refer
list->vector
length
code-builder-put-insn-arg2!
code-builder-put-insn-arg1!
code-builder-put-insn-arg0!
code-builder-emit
code-builder-append!
code-builder-put-extra5!
code-builder-put-extra4!
code-builder-put-extra3!
code-builder-put-extra2!
code-builder-put-extra1!
make-code-builder
pass4/fixup-labels
pass3/find-sets
pass3/find-free
append!
append2
append
%get-closure-name
%start-process
%dup
%confstr
%call-process
set-source-info!
vector->list
read
char>?
char>=?
char<?
char<=?
symbol?
load
procedure?
memv
macroexpand-1
exit
assv
assoc
assq
apply
eval-compiled
eval
source-info
regexp-replace-all
regexp-replace
vector
close-input-port
open-file-input-port
open-file-output-port
get-bytevector-n
standard-error-port
standard-output-port
standard-input-port
bytevector-length
sys-get-bytevector
sys-open-bytevector-output-port
eof-object
make-transcoder
utf-16-codec
utf-8-codec
latin-1-codec
transcoded-port
get-bytevector-all
get-bytevector-some
get-bytevector-n!
set-port-position!
port-position
port-has-set-port-position!?
port-has-port-position?
bytevector-u8-set!
output-port-buffer-mode
flush-output-port
put-string
put-u8
get-u8
make-custom-textual-output-port
make-custom-textual-input-port
make-custom-binary-output-port
make-custom-binary-input-port
pair?
vm/apply
values
current-error-port
eq-hashtable-copy
equal-hash
symbol-hash
string-ci-hash
eqv-hash
string-hash
hashtable-keys
hashtable-ref
hashtable-set!
make-eqv-hashtable
make-eq-hashtable
get-timeofday
string-ref
symbol->string
boolean?
member
eqv?
eq?
memq
list
list?
vector?
boolean=?
symbol=?
cddr
cdddr
cddddr
cdddar
cddar
cddadr
cddaar
cdar
cdadr
cdaddr
cdadar
cdaar
cdaadr
cdaaar
cadr
caddr
cadddr
caddar
cadar
cadadr
cadaar
caar
caadr
caaddr
caadar
caaar
caaadr
caaaar
string=?
gensym
write
char?
set-current-output-port!
set-current-input-port!
current-output-port
current-input-port
format
integer->char
char->integer
string->regexp
get-output-string
delete-file
file-exists?
directory-list
get-remaining-input-string
digit->integer
close-output-port
sys-port-seek
open-output-string
open-string-input-port
equal?
get-environment-variables
get-environment-variable
string?
char=?
peek-char
read-char
eof-object?
reverse
number->string
string
string-split
string-append
string->number
string->symbol
string-length
string-set!
make-string
rxmatch-substring
rxmatch-before
rxmatch-after
rxmatch-end
rxmatch-start
regexp->string
regexp?
rxmatch
sys-display
set-cdr!
set-car!
null?
cdr
car
cons*
cons
number?

