(define (%%selfboot-yuniconfig-get-polyfill-path sym)
  (let ((n (assoc sym yuni/polyfills)))
   (cond
     (n (cdr n))
     (else
       (write (list 'UNKNOWN: sym)) (newline)
       (error "Unknown polyfill" sym)))))

(define yuni/polyfills
  '(
    ;; Std, non-R5RS
    (boolean=? . "lib-runtime/generic/std/boolean_eqp.scm")
    (floor-quotient . "lib-runtime/generic/std/floor-quotient.scm")
    (floor-remainder . "lib-runtime/generic/std/floor-remainder.scm")
    (floor/ . "lib-runtime/generic/std/floor_div.scm")
    (list-copy . "lib-runtime/generic/std/list-copy.scm")
    (list-set! . "lib-runtime/generic/std/list-set_x.scm")
    (make-list . "lib-runtime/generic/std/make-list.scm")
    (modulo . "lib-runtime/generic/std/modulo.scm")
    (quotient . "lib-runtime/generic/std/quotient.scm")
    (remainder . "lib-runtime/generic/std/remainder.scm")
    (string-copy . "lib-runtime/generic/std/string-copy.scm")
    (string-for-each . "lib-runtime/generic/std/string-for-each.scm")
    (string-map . "lib-runtime/generic/std/string-map.scm")
    (string->list . "lib-runtime/generic/std/string_to_list.scm")
    (string->vector . "lib-runtime/generic/std/string_to_vector.scm")
    (truncate-quotient . "lib-runtime/generic/std/truncate-quotient.scm")
    (truncate-remainder . "lib-runtime/generic/std/truncate-remainder.scm")
    (truncate/ . "lib-runtime/generic/std/truncate_div.scm")
    (vector-append . "lib-runtime/generic/std/vector-append.scm")
    (vector-copy . "lib-runtime/generic/std/vector-copy.scm")
    (vector-copy! . "lib-runtime/generic/std/vector-copy_x.scm")
    (vector-fill! . "lib-runtime/generic/std/vector-fill_x.scm")
    (vector-for-each . "lib-runtime/generic/std/vector-for-each.scm")
    (vector-map . "lib-runtime/generic/std/vector-map.scm")
    (vector->list . "lib-runtime/generic/std/vector_to_list.scm")
    (vector->string . "lib-runtime/generic/std/vector_to_string.scm")
    ))
